added homework
vvfcypress/JS pull request #1
Opened 2023-10-02 15:00 UTC by vvfcypress

2023-10-02 15:35 UTC, DmytroSanitarskyi requested changes

2023-10-02 15:35 UTC, DmytroSanitarskyi commented on JS-hw-1.js
> +
`    if (price < 1000 || price > 1900)
`
це варіант без оператора заперечення) зробіть з запереченням по аналогії

2023-10-02 15:35 UTC, DmytroSanitarskyi commented on JS-hw-1.js
> +if((a < b && b < c) || (c < b && b < a)){
правильно, але потрібно було використати вкладені if:
```

 let a = 7, b = 1, c = 30
    let avg

    if (a > b) {
    if (a > c) {
        // a - max
        if (b > c)
        avg = b
        else
        avg = c
    }
...
```

2023-10-02 15:35 UTC, DmytroSanitarskyi commented on JS-hw-1.js
> +    myArray.push((i1+1)*2);
загалом все правильно, але можна було простіше зробити:
```

const myArray = [];

for (let i = 2; i < 10; i += 2) {
  myArray.push(i);
}
```

2023-10-02 15:35 UTC, DmytroSanitarskyi commented on JS-hw-1.js
> +
тут взяли правильний напрямок, саму логіку прописали правильно і якщо виправити рядок де ви додаєте значення до змінної та інші дрібні помилки, то буде щось таке:

```
let total = 1;
let myArray2 = [2, 3, 4, 5, 6];

for(let i = 0; i < myArray2.length; i++){

    total = myArray2[i] + total;

}
console.log(total);
```

2023-10-02 15:35 UTC, DmytroSanitarskyi commented on JS-hw-1.js
> +
тут має бути цикл, котрий по черзі виведе всі числа в консоль

2023-10-02 15:35 UTC, DmytroSanitarskyi commented on JS-hw-1.js
> +
```
const arr = [[1, 2], [3, 4], [5, 6, 7]];

let result = 1;

for (let i = 0; i < arr.length; i++) {
    for (let j = 0; j < arr[i].length; j++) {
        result = result * arr[i][j]
    }
}

console.log(result);
```

2023-10-11 19:07 UTC, SanitarskyiDmytro approved these changes

2023-10-14 14:57 UTC, merged